# Site settings
title: Marco Berta - AI engineer
subtitle: "AI Engineer - Data Scientist - Researcher"
email: marco.berta@aiengineering.fr
url: https://marco.berta.com
description: "my description"
keywords: "Python, AI, Machine Learning, Deep Learning, Data Science, Data Engineer"
skills: "Freelance AI Engineer | Azure certified Data Scientist "
meta_author: Marco Berta

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static   
#(without the leading hash-tag)
color:
  primary: 0033cc # Blue
  primary-rgb: 0,51,204
  secondary: 3366ff # Lighter blue
  white: ffffff # White color
  secondary-dark: 001a66 # Dark blue

# Footer settings
footer:
  copyright: Dr. Marco Berta
  location: Home Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/marco-berta
  - title: github
    url: http://github.com/opsabarsec
  - title: youtube
    url: https://www.youtube.com/@marcoberta6353
  - title: medium
    url: https://medium.com/@marcoberta

# Postal address (add as many lines as necessary)
address:
  - line: 13006 Marseille, France 

# Credits content
credits: 'Automate boring tasks with AI and boost your business'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
