# Site settings
title: Marco Berta - AI engineer
subtitle: "AI Engineer - Data Scientist - Researcher"
email: marco.berta@aiengineering.fr
url: https://marco.berta.com
description: "my description"
keywords: "Python, AI, Machine Learning, Deep Learning, Data Science, Data Engineer"
skills: "Freelance AI Engineer | Azure certified Data Scientist "
meta_author: Marco Berta

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

  without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  white: ffffff #White color
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Marco Berta
  location: Marseille, France
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/marco-berta
  - title: github
    url: http://github.com/opsabarsec
  - title: youtube
    url: https://www.youtube.com/@marcoberta6353
  - title: medium
    url: https://medium.com/@marcoberta

# Postal address (add as many lines as necessary)
address:
  - line: 13006 Marseille, France 

# Credits content
credits: 'Marco Berta 2025'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
